/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo02;

import javax.swing.JOptionPane;

/**
 *
 * @author teymr
 */
public class frmPantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPantallaPrincipal
     */
    public frmPantallaPrincipal() {
        initComponents();
    }

    //**********************************************************
    private void fn_Sumar()
    {
    int mNumero1 = Integer.parseInt(txtValor1.getText());
    int mNumero2 = Integer.parseInt(txtValor2.getText());
    int mResultado = mNumero1+mNumero2;
    JOptionPane.showMessageDialog(null, mResultado);
    }
    private void fn_Multiplicar()
    {
    int mNumero1 = Integer.parseInt(txtValor1.getText());
    int mNumero2 = Integer.parseInt(txtValor2.getText());
    int mResultado = mNumero1*mNumero2;
    JOptionPane.showMessageDialog(null, mResultado);
    }
    private void fn_MultiplicarV2(int pNumero1, int pNumero2)
    {
    int mResultado = pNumero1*pNumero2;
    JOptionPane.showMessageDialog(null, mResultado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        txtValor2 = new javax.swing.JTextField();
        btnSumar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        btnMultiplicar = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnConcatenar = new javax.swing.JButton();
        btnSumaSiMayor = new javax.swing.JButton();
        btnsumarconfuncion = new javax.swing.JButton();
        btnmultiplicarconfuncion = new javax.swing.JButton();
        btnFuncionconparametros = new javax.swing.JButton();
        btnNombreDeMes = new javax.swing.JButton();
        btnCicloFor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Bienvenido a mi Aplicacion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Digite el segundo valor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Digite el primer valor");

        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResultado.setText("Resultado");

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnResta.setText("Resta");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        btnConcatenar.setText("Concatenar");
        btnConcatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatenarActionPerformed(evt);
            }
        });

        btnSumaSiMayor.setText("Suma Si Mayor");
        btnSumaSiMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaSiMayorActionPerformed(evt);
            }
        });

        btnsumarconfuncion.setText("Sumar Con Funcion");
        btnsumarconfuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarconfuncionActionPerformed(evt);
            }
        });

        btnmultiplicarconfuncion.setText("Multiplicar Con Funcion");
        btnmultiplicarconfuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiplicarconfuncionActionPerformed(evt);
            }
        });

        btnFuncionconparametros.setText("Funcion Con Parametros");
        btnFuncionconparametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionconparametrosActionPerformed(evt);
            }
        });

        btnNombreDeMes.setText("Nombre del Mes");
        btnNombreDeMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreDeMesActionPerformed(evt);
            }
        });

        btnCicloFor.setText("Ciclo FOR");
        btnCicloFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCicloForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtValor1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtValor2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnSumar)
                                .addGap(41, 41, 41)
                                .addComponent(btnResta)
                                .addGap(26, 26, 26)
                                .addComponent(btnMultiplicar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(btnDividir)
                                .addGap(72, 72, 72))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnConcatenar)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSumaSiMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsumarconfuncion)
                                .addGap(18, 18, 18)
                                .addComponent(btnmultiplicarconfuncion))
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFuncionconparametros, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNombreDeMes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCicloFor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConcatenar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSumaSiMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnmultiplicarconfuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsumarconfuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFuncionconparametros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNombreDeMes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCicloFor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
        int mNumero1 = Integer.parseInt(txtValor1.getText());
        int mNumero2 = Integer.parseInt(txtValor2.getText());
        int mResultado = mNumero1 + mNumero2;
        lblResultado.setText(String.valueOf(mResultado));
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        // TODO add your handling code here:
        int mNumero1 = Integer.parseInt(txtValor1.getText());
        int mNumero2 = Integer.parseInt(txtValor2.getText());
        int mResultado = mNumero1 * mNumero2;
        lblResultado.setText(String.valueOf(mResultado));
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        // TODO add your handling code here:
        int mNumero1 = Integer.parseInt(txtValor1.getText());
        int mNumero2 = Integer.parseInt(txtValor2.getText());
        int mResultado = mNumero1 - mNumero2;
        lblResultado.setText(String.valueOf(mResultado));
        
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // TODO add your handling code here:
        int mNumero1 = Integer.parseInt(txtValor1.getText());
        int mNumero2 = Integer.parseInt(txtValor2.getText());
        int mResultado = mNumero1 / mNumero2;
        lblResultado.setText(String.valueOf(mResultado));
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatenarActionPerformed
        // TODO add your handling code here:
        String mNumero1 = txtValor1.getText();
        String mNumero2 = txtValor2.getText();
        String mResultado = mNumero1.trim() + " " + mNumero2.trim();
        lblResultado.setText(mResultado);
        JOptionPane.showMessageDialog(null," El nombre digitado es " + mResultado);
        
    }//GEN-LAST:event_btnConcatenarActionPerformed

    private void btnSumaSiMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaSiMayorActionPerformed
        // TODO add your handling code here:
            int mNumero1 = Integer.parseInt(txtValor1.getText());
            int mNumero2 = Integer.parseInt(txtValor2.getText());
            if((mNumero1>=100)&&(mNumero2>=100))
        {
            int mResultado = mNumero1 + mNumero2;
            lblResultado.setText(String.valueOf(mResultado));
            JOptionPane.showMessageDialog(null, mResultado);
        }
        else
        {
        if(mNumero1>100)    
            {
            int mResultado = mNumero1 - mNumero2;
            lblResultado.setText(String.valueOf(mResultado));
            JOptionPane.showMessageDialog(null, mResultado); 
        }
        else
         {
            int mResultado = mNumero1 * mNumero2;
            lblResultado.setText(String.valueOf(mResultado));
            JOptionPane.showMessageDialog(null, mResultado); 
        }
        }
    }//GEN-LAST:event_btnSumaSiMayorActionPerformed

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void btnsumarconfuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarconfuncionActionPerformed
        // TODO add your handling code here:
        fn_Sumar();
    }//GEN-LAST:event_btnsumarconfuncionActionPerformed

    private void btnmultiplicarconfuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiplicarconfuncionActionPerformed
        // TODO add your handling code here:
        fn_Multiplicar();
    }//GEN-LAST:event_btnmultiplicarconfuncionActionPerformed
    
    private void btnFuncionconparametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionconparametrosActionPerformed
       if(!txtValor1.getText().trim().equals(""))
       {
        if(!txtValor2.getText().equals(""))
        {
            int mNumero1 = Integer.parseInt(txtValor1.getText());
            int mNumero2 = Integer.parseInt(txtValor2.getText());    
            fn_MultiplicarV2(mNumero1,mNumero2);
        }
       else   
        {    
       JOptionPane.showMessageDialog(null, "No Hay datos en valor 2 para procesar");      
        }        
       }
       else        
       {
       JOptionPane.showMessageDialog(null, "No hay datos en valor 1 para procesar");
       }
               
    }//GEN-LAST:event_btnFuncionconparametrosActionPerformed

    private void btnNombreDeMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreDeMesActionPerformed
        int mNumeroMes = Integer.parseInt(txtValor1.getText()); 
        switch(mNumeroMes)
        {
            case 1:     
              JOptionPane.showMessageDialog(null, "El mes es Enero");
              break;
            case 2:
              JOptionPane.showMessageDialog(null,"El mes es Febrero");
               break;
         case 3:     
              JOptionPane.showMessageDialog(null, "El mes es Marzo");
              break;
            case 4:
              JOptionPane.showMessageDialog(null,"El mes es Abril");
               break;
          case 5:     
              JOptionPane.showMessageDialog(null, "El mes es Mayo");
              break;
            case 6:
              JOptionPane.showMessageDialog(null,"El mes es Junio");
               break;
         case 7:     
              JOptionPane.showMessageDialog(null, "El mes es Julio");
              break;
            case 8:
              JOptionPane.showMessageDialog(null,"El mes es Agosto");
               break;
         case 9:     
              JOptionPane.showMessageDialog(null, "El mes es Septiembre");
              break;
            case 10:
              JOptionPane.showMessageDialog(null,"El mes es Octubre");
               break;
          case 11:     
              JOptionPane.showMessageDialog(null, "El mes es Noviembre");
              break;
            case 12:
              JOptionPane.showMessageDialog(null,"El mes es Diciembre");
               break;
            default:
             if (mNumeroMes<=12) 
             {
             JOptionPane.showMessageDialog(null,"El mes digitado es mayor a Junio");
             }
             else
            {
            JOptionPane.showMessageDialog(null,"El mes Digitado no es valido");
            }
             break;
    }//GEN-LAST:event_btnNombreDeMesActionPerformed
    }
    private void btnCicloForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCicloForActionPerformed
       int mCantidadVeces = Integer.parseInt(txtValor1.getText());  
       int mContador = 0;
       for(int i=1; i<=mCantidadVeces; i++)
       {
           mContador=1;
       }  
       JOptionPane.showMessageDialog(null,"El ciclo se ejecuto" + mContador);
    }//GEN-LAST:event_btnCicloForActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCicloFor;
    private javax.swing.JButton btnConcatenar;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnFuncionconparametros;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnNombreDeMes;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSumaSiMayor;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnmultiplicarconfuncion;
    private javax.swing.JButton btnsumarconfuncion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
